### ISSUE TITLE
[Feat] 전역 예외처리 기능 구현

### ISSUE THREAD

**Issue by luke0408** [Team-AESP/Service-Server#5]
## Describtion
> 전역 예외 처리를 위한 글로벌 익셉션 핸들러 구현

## To-DO
> 작업 계획 작성
- [x] 글로벌 입셉션 핸들러 구현
- [x] 핸들러 동작 테스트
  - [x] 테스트 환경 구축
  - [x] 실제 동작 테스트
